//
// Created by Moshe Sheena on 08/10/2017.
//

#ifndef ZOO_MANAGEMENT_SYSTEM_ANIMALCLASSIFY_H
#define ZOO_MANAGEMENT_SYSTEM_ANIMALCLASSIFY_H

const char* animalClasses[] = {"LAND", "MARINE", "AMPHIBIAN"};

enum eAnimalClass{LAND, MARINE, AMPHIBIAN};


#endif //ZOO_MANAGEMENT_SYSTEM_ANIMALCLASSIFY_H
